### ISSUE TITLE
copy & paste enhancements

### ISSUE THREAD

**Issue by tborychowski** [tborychowski/filer#13]
### Tasks
- [ ] flash the newly pasted item yellow (or sth.)
- [ ] visual & progress for copy & paste/move
    - a tooltip over statusbar on copy as a skateboard (first step)?
- [ ] allow to pause/resume & cancel an operation
- [ ] show dock progress-bar

### Notes
- evaluate [cpy](https://github.com/sindresorhus/cpy) for copy with progress
- write one from scratch to support the following API:
    - `.copy()`
    - `.move()`
    - `.cancel()`
    - `.pause()`
    - `.on('progress',...)`
- it should allow to set the `OVERWRITE` flag to:
    - `overwrite` existing item
    - `skip` existing item (if they have the same name)
    - "keep both items" - rename the new item to `...(1)`
    - and bulk versions of the above (overwrite all, skip all, keep all)
- It should first copy everything that does not cause problems and THEN ask what to do with the remaining ones
