### ISSUE TITLE
cache folder view

### ISSUE THREAD

**Issue by tborychowski** [tborychowski/filer#9]
- cache folders (so it's fast to start-up)
- sync in background
- maybe frequently opened first...

### Tasks
- [x] select storage (better-sqlite3?)
- [x] prepare abstraction layer for basic operations ([example](https://github.com/tborychowski/tim/blob/sqlite/app/services/DB.js) here):
    - read folder data (if exists) before open
    - store (add/update) folder data after open
- [x] integrate with `Files` ops

**Comment by tborychowski** [comment]
won't fix, as it uses more CPU than just directly reading stuff from disk...
